# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User Seeds
User.create(name: "Rod", username: "RodCardenas", email: "rod@gmail.com")
User.create(name: "Eliot", username: "EliotHowes", email: "eliot@gmail.com")
User.create(name: "Adnan", username: "AdnanAzim", email: "adnan@gmail.com")
User.create(name: "Mary", username: "MarySelig", email: "mary@gmail.com")
User.create(name: "Nick", username: "NickCharlet", email: "nick@gmail.com")
User.create(name: "Harry", username: "HarryChopra", email: "harry@gmail.com")

# Game Seeds
Game.create(user_id: 1)

# Card Seeds - online
# Card.create(name: "1", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_01_aatrox.png", top_value: 3, right_value: 10, bottom_value: 5, left_value: 6)
# Card.create(name: "2", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_02_ahri.png", top_value: 9, right_value: 7, bottom_value: 6, left_value: 3)
# Card.create(name: "3", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_03_akali.png", top_value: 5, right_value: 5, bottom_value: 9, left_value: 8)
# Card.create(name: "4", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_04_alistar.png", top_value: 6, right_value: 6, bottom_value: 6, left_value: 6)
# Card.create(name: "5", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_05_amumu.png", top_value: 5, right_value: 3, bottom_value: 8, left_value: 3)
# Card.create(name: "6", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_06_anivia.png", top_value: 8, right_value: 5, bottom_value: 4, left_value: 3)
# Card.create(name: "7", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_07_annie.png", top_value: 7, right_value: 2, bottom_value: 4, left_value: 5)
# Card.create(name: "8", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_08_ashe.png", top_value: 4, right_value: 9, bottom_value: 6, left_value: 2)
# Card.create(name: "9", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_09_aurelion_sol.png", top_value: 5, right_value: 3, bottom_value: 9, left_value: 7)
# Card.create(name: "10", img: "https://mod-3-project.s3.eu-west-2.amazonaws.com/card_10_azir.png", top_value: 9, right_value: 3, bottom_value: 2, left_value: 9)


# ../backend/app/assets/images/rift_map.png
# Card Seeds - offline
Card.create(name: "1", img: '../backend/app/assets/images/card_01_aatrox.png', top_value: 3, right_value: 10, bottom_value: 5, left_value: 6)
Card.create(name: "2", img: "../backend/app/assets/images/card_02_ahri.png", top_value: 9, right_value: 7, bottom_value: 6, left_value: 3)
Card.create(name: "3", img: "../backend/app/assets/images/card_03_akali.png", top_value: 5, right_value: 5, bottom_value: 9, left_value: 8)
Card.create(name: "4", img: "../backend/app/assets/images/card_04_alistar.png", top_value: 6, right_value: 6, bottom_value: 6, left_value: 6)
Card.create(name: "5", img: "../backend/app/assets/images/card_05_amumu.png", top_value: 5, right_value: 3, bottom_value: 8, left_value: 3)
Card.create(name: "6", img: "../backend/app/assets/images/card_06_anivia.png", top_value: 8, right_value: 5, bottom_value: 4, left_value: 3)
Card.create(name: "7", img: "../backend/app/assets/images/card_07_annie.png", top_value: 7, right_value: 2, bottom_value: 4, left_value: 5)
Card.create(name: "8", img: "../backend/app/assets/images/card_08_ashe.png", top_value: 4, right_value: 9, bottom_value: 6, left_value: 2)
Card.create(name: "9", img: "../backend/app/assets/images/card_09_aurelion_sol.png", top_value: 5, right_value: 3, bottom_value: 9, left_value: 7)
Card.create(name: "10", img: "../backend/app/assets/images/card_10_azir.png", top_value: 9, right_value: 3, bottom_value: 2, left_value: 9)
Card.create(name: "11", img: "../backend/app/assets/images/card_11_bard.png", top_value: 6, right_value: 3, bottom_value: 2, left_value: 3)
Card.create(name: "12", img: "../backend/app/assets/images/card_12_blitzcrank.png", top_value: 6, right_value: 3, bottom_value: 8, left_value: 7)
Card.create(name: "13", img: "../backend/app/assets/images/card_13_brand.png", top_value: 8, right_value: 7, bottom_value: 2, left_value: 4)
Card.create(name: "14", img: "../backend/app/assets/images/card_14_braum.png", top_value: 5, right_value: 5, bottom_value: 5, left_value: 5)
Card.create(name: "15", img: "../backend/app/assets/images/card_15_caitlyn.png", top_value: 10, right_value: 3, bottom_value: 3, left_value: 3)
Card.create(name: "16", img: "../backend/app/assets/images/card_16_camille.png", top_value: 7, right_value: 8, bottom_value: 3, left_value: 5)
Card.create(name: "17", img: "../backend/app/assets/images/card_17_cassiopeia.png", top_value: 5, right_value: 3, bottom_value: 7, left_value: 6)
Card.create(name: "18", img: "../backend/app/assets/images/card_18_cho_gath.png", top_value: 5, right_value: 2, bottom_value: 3, left_value: 7)
Card.create(name: "19", img: "../backend/app/assets/images/card_19_corki.png", top_value: 2, right_value: 2, bottom_value: 3, left_value: 10)
Card.create(name: "20", img: "../backend/app/assets/images/card_20_darius.png", top_value: 3, right_value: 7, bottom_value: 3, left_value: 6)
Card.create(name: "21", img: "../backend/app/assets/images/card_21_diana.png", top_value: 6, right_value: 8, bottom_value: 2, left_value: 2)
Card.create(name: "22", img: "../backend/app/assets/images/card_22_dr_mundo.png", top_value: 5, right_value: 3, bottom_value: 9, left_value: 3)
Card.create(name: "23", img: "../backend/app/assets/images/card_23_draven.png", top_value: 1, right_value: 4, bottom_value: 9, left_value: 4)
Card.create(name: "24", img: "../backend/app/assets/images/card_24_ekko.png", top_value: 5, right_value: 6, bottom_value: 7, left_value: 6)
Card.create(name: "26", img: "../backend/app/assets/images/card_25_elise.png", top_value: 3, right_value: 4, bottom_value: 4, left_value: 5)
Card.create(name: "27", img: "../backend/app/assets/images/card_26_evelyn.png", top_value: 6, right_value: 8, bottom_value: 4, left_value: 3)
Card.create(name: "28", img: "../backend/app/assets/images/card_27_ezreal.png", top_value: 6, right_value: 8, bottom_value: 4, left_value: 9)
Card.create(name: "29", img: "../backend/app/assets/images/card_28_fiddle.png", top_value: 2, right_value: 3, bottom_value: 4, left_value: 9)
Card.create(name: "30", img: "../backend/app/assets/images/card_29_fiora.png", top_value: 6, right_value: 9, bottom_value: 5, left_value: 2)
Card.create(name: "31", img: "../backend/app/assets/images/card_30_fizz.png", top_value: 4, right_value: 2, bottom_value: 9, left_value: 2)
Card.create(name: "32", img: "../backend/app/assets/images/card_31_galio.png", top_value: 4, right_value: 7, bottom_value: 4, left_value: 4)
Card.create(name: "33", img: "../backend/app/assets/images/card_32_gangplank.png", top_value: 5, right_value: 2, bottom_value: 3, left_value: 7)
Card.create(name: "34", img: "../backend/app/assets/images/card_33_garen.png", top_value: 3, right_value: 6, bottom_value: 8, left_value: 3)
Card.create(name: "35", img: "../backend/app/assets/images/card_34_gnar.png", top_value: 8, right_value: 4, bottom_value: 5, left_value: 2)
Card.create(name: "36", img: "../backend/app/assets/images/card_35_gragas.png", top_value: 5, right_value: 2, bottom_value: 9, left_value: 1)
Card.create(name: "36", img: "../backend/app/assets/images/card_36_graves.png", top_value: 2, right_value: 10, bottom_value: 3, left_value: 1)
Card.create(name: "37", img: "../backend/app/assets/images/card_37_hecarim.png", top_value: 4, right_value: 6, bottom_value: 8, left_value: 3)
Card.create(name: "38", img: "../backend/app/assets/images/card_38_heimerdinger.png", top_value: 5, right_value: 3, bottom_value: 6, left_value: 8)
Card.create(name: "39", img: "../backend/app/assets/images/card_39_illaoi.png", top_value: 7, right_value: 6, bottom_value: 6, left_value: 4)
Card.create(name: "40", img: "../backend/app/assets/images/card_40_irelia.png", top_value: 4, right_value: 7, bottom_value: 8, left_value: 2)
Card.create(name: "41", img: "../backend/app/assets/images/card_41_ivern.png", top_value: 6, right_value: 2, bottom_value: 3, left_value: 5)
Card.create(name: "42", img: "../backend/app/assets/images/card_42_janna.png", top_value: 7, right_value: 5, bottom_value: 5, left_value: 2)
Card.create(name: "43", img: "../backend/app/assets/images/card_43_jarvan.png", top_value: 3, right_value: 4, bottom_value: 7, left_value: 8)
Card.create(name: "44", img: "../backend/app/assets/images/card_44_jax.png", top_value: 7, right_value: 7, bottom_value: 7, left_value: 7)
Card.create(name: "45", img: "../backend/app/assets/images/card_45_jayce.png", top_value: 3, right_value: 3, bottom_value: 5, left_value: 8)
Card.create(name: "46", img: "../backend/app/assets/images/card_46_jhin.png", top_value: 3, right_value: 10, bottom_value: 4, left_value: 2)
Card.create(name: "47", img: "../backend/app/assets/images/card_47_jinx.png", top_value: 4, right_value: 5, bottom_value: 10, left_value: 3)
Card.create(name: "48", img: "../backend/app/assets/images/card_48_kai_sa.png", top_value: 7, right_value: 6, bottom_value: 8, left_value: 4)
Card.create(name: "49", img: "../backend/app/assets/images/card_49_kalista.png", top_value: 8, right_value: 8, bottom_value: 8, left_value: 1)
Card.create(name: "50", img: "../backend/app/assets/images/card_50_karma.png", top_value: 4, right_value: 4, bottom_value: 5, left_value: 6)
Card.create(name: "51", img: "../backend/app/assets/images/card_51_karthus.png", top_value: 4, right_value: 7, bottom_value: 6, left_value: 4)
Card.create(name: "52", img: "../backend/app/assets/images/card_52_katerina.png", top_value: 5, right_value: 3, bottom_value: 5, left_value: 10)
Card.create(name: "53", img: "../backend/app/assets/images/card_53_kayle.png", top_value: 9, right_value: 2, bottom_value: 4, left_value: 8)
Card.create(name: "54", img: "../backend/app/assets/images/card_54_kayn.png", top_value: 9, right_value: 9, bottom_value: 3, left_value: 2)
Card.create(name: "55", img: "../backend/app/assets/images/card_55_kennen.png", top_value: 4, right_value: 3, bottom_value: 5, left_value: 7)
Card.create(name: "56", img: "../backend/app/assets/images/card_56_kha_zix.png", top_value: 6, right_value: 7, bottom_value: 5, left_value: 3)
Card.create(name: "57", img: "../backend/app/assets/images/card_57_kindred.png", top_value: 3, right_value: 6, bottom_value: 7, left_value: 3)
Card.create(name: "58", img: "../backend/app/assets/images/card_58_kled.png", top_value: 7, right_value: 5, bottom_value: 6, left_value: 9)
Card.create(name: "59", img: "../backend/app/assets/images/card_59_kog_maw.png", top_value: 3, right_value: 3, bottom_value: 10, left_value: 1)
Card.create(name: "60", img: "../backend/app/assets/images/card_60_leblanc.png", top_value: 3, right_value: 7, bottom_value: 8, left_value: 7)
Card.create(name: "61", img: "../backend/app/assets/images/card_61_lee_sin.png", top_value: 3, right_value: 3, bottom_value: 9, left_value: 5)
Card.create(name: "62", img: "../backend/app/assets/images/card_62_leona.png", top_value: 5, right_value: 7, bottom_value: 7, left_value: 3)
Card.create(name: "63", img: "../backend/app/assets/images/card_63_lissandra.png", top_value: 5, right_value: 7, bottom_value: 8, left_value: 6)
Card.create(name: "64", img: "../backend/app/assets/images/card_64_lucian.png", top_value: 8, right_value: 7, bottom_value: 6, left_value: 7)
Card.create(name: "65", img: "../backend/app/assets/images/card_65_lulu.png", top_value: 5, right_value: 7, bottom_value: 4, left_value: 4)
Card.create(name: "66", img: "../backend/app/assets/images/card_66_lux.png", top_value: 8, right_value: 7, bottom_value: 5, left_value: 3)
Card.create(name: "67", img: "../backend/app/assets/images/card_67_malphite.png", top_value: 6, right_value: 7, bottom_value: 6, left_value: 6)
Card.create(name: "68", img: "../backend/app/assets/images/card_68_malzahar.png", top_value: 5, right_value: 6, bottom_value: 7, left_value: 4)
Card.create(name: "69", img: "../backend/app/assets/images/card_69_maokai.png", top_value: 5, right_value: 3, bottom_value: 8, left_value: 5)
Card.create(name: "70", img: "../backend/app/assets/images/card_70_yi.png", top_value: 7, right_value: 4, bottom_value: 2, left_value: 6)
Card.create(name: "71", img: "../backend/app/assets/images/card_71_miss_fortune.png", top_value: 8, right_value: 7, bottom_value: 2, left_value: 2)
Card.create(name: "72", img: "../backend/app/assets/images/card_72_mordekaiser.png", top_value: 5, right_value: 7, bottom_value: 4, left_value: 10)



# User_Card Seeds
UserCard.create(user_id: 1, card_id: 1)
UserCard.create(user_id: 1, card_id: 2)
UserCard.create(user_id: 1, card_id: 3)
UserCard.create(user_id: 1, card_id: 4)
UserCard.create(user_id: 1, card_id: 5)
UserCard.create(user_id: 1, card_id: 6)
UserCard.create(user_id: 1, card_id: 7)
UserCard.create(user_id: 1, card_id: 8)
UserCard.create(user_id: 1, card_id: 9)
UserCard.create(user_id: 1, card_id: 10)